# Generated by Django 5.2.3 on 2025-08-01 23:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0039_category_deleted_at_category_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 2, 23, 34, 23, 51148, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 2, 23, 34, 23, 51148, tzinfo=datetime.timezone.utc)),
        ),
    ]
