# Generated by Django 5.2.3 on 2025-08-02 00:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0040_alter_subtask_deadline_alter_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 3, 0, 12, 34, 454409, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 3, 0, 12, 34, 454409, tzinfo=datetime.timezone.utc)),
        ),
    ]
