# Generated by Django 5.2.4 on 2025-08-02 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='language',
            field=models.CharField(choices=[('py', 'Python'), ('c#', 'C#'), ('java', 'Java')]),
        ),
    ]
