# Generated by Django 5.2.4 on 2025-08-02 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='language',
            field=models.CharField(choices=[('c#', 'C#'), ('py', 'Python'), ('java', 'Java')]),
        ),
    ]
